#ifndef ERROR_H
#define ERROR_H

#define TUPLE_E_OUT_OF_RANGE -1
#define TUPLE_E_INVALID_TYPE -2
#define TUPLE_E_INVALID_OP -3
#define SERVER_E_OVERLOAD_MESSAGE_BUFFER -4
#define SERVER_E_OVERLOAD_CLIENT_QUEUE -5

#endif
